server:
  port: 8080
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&autoReconnectForPools=true&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 5000ms
    max-idle: 8
    min-idle； 1
mybatis:
  type-aliases-package: com.fpi.test.model

